# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jonathan Mares
email: jmares93@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Jonathan Mares. Engineer, Programmer, Musician.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jonathanmares.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

sass:
    sass_dir: _sass

# Server Config options
livereload: true    # You no longer need to include --livereload
reload_port: 5678    # If you don't want to use the default port